# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

search_shortcut: off

matches:
  # Date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d %H:%M:%S"
  - trigger: ":ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d-%H-%M-%S"
  - trigger: ":udate"
    replace: "Update: {{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d %H:%M:%S"

  # Upgrade
  - trigger: ":up-latex"
    replace: "tlmgr update --all --self --reinstall-forcibly-removed"

  # Password
  - trigger: ":y]"
    replace: "y]A-Sr.%2&"
  - trigger: ":Wk"
    replace: "Wk2XMk,Eh"

  # Standard UUID.
  - trigger: ":uuid"
    replace: "{{uuid}}"
    propagate_case: true
    uppercase_style: uppercase
    vars:
      - name: uuid
        type: script
        params:
          args:
            - C:/Users/zhong/miniconda3/python
            - -c
            - |
              import uuid
              print(uuid.uuid4())

  # Non-dashed UUID.
  - trigger: ":nuuid"
    replace: "{{uuid_nodash}}"
    propagate_case: true
    uppercase_style: uppercase
    vars:
      - name: uuid_nodash
        type: script
        params:
          args:
            - C:/Users/zhong/miniconda3/python
            - -c
            - |
              import uuid
              print(str(uuid.uuid4()).replace('-', ''))
