profileParsersText: |-
  parsers: # array
    - reg: .*
      yaml:
        append-proxies:
          - name: EasyConnect
            type: socks5
            server: 127.0.0.1
            port: 1080
            udp: true
        append-proxy-groups:
          - name: Nankai University
            type: select
            proxies:
              - DIRECT
              - EasyConnect
        prepend-rules:
          - IP-CIDR,10.0.0.0/8,Nankai University
          - DOMAIN,blog.alumik.cn,DIRECT
          - DOMAIN-SUFFIX,cn.mm.bing.net,DIRECT
          - DOMAIN,tracedseals.starfieldtech.com,REJECT
          - DOMAIN,pic.picnewsss.com,REJECT
showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true